### ISSUE TITLE
Release for Coq 8.18

### ISSUE THREAD

**Issue by palmskog** [damien-pous/coinduction#15]
Any chance of a release/tag for Coq 8.18 that includes the hint mode from #14?

I can take care of the opam packaging if the tag is set. Feel free to use anything from the [8.18 branch in my fork](https://github.com/palmskog/coinduction/tree/8.18) - in fact, [this commit](https://github.com/palmskog/coinduction/commit/48d29cea44d2e90384809cac8ea3fd0d36cf60de) will suffice to get 8.18-ready code from current `master`.

**Comment by damien-pous** [comment]
Hi @palmskog 
Just to reassure you that I'm on it: should be able to double check everything this Friday.

**Comment by damien-pous** [comment]
I'm puzzled...

I use opam and I have switches for Coq 8.16.1,17.1,18.0
The lib compiles with those three versions of Coq (on my machine) with [Tactics.revert] in src/reification.ml
But on the CI, it needs [Generalize.revert] for Coq 8.18

Any idea?

**Comment by palmskog** [comment]
@damien-pous I think I could fix these problems with a PR to your `8.18` branch.

The basic idea is that we have `tclTHEN (Generalize.revert [rname])` to be compatible with Coq `master` and Coq's CI, but then 8.16 to 8.18 needs this to be `tclTHEN (Tactics.revert [rname])`. So in the `8.18` branch CI, you can test everything but `coq:dev`/Coq `master`.

**Comment by palmskog** [comment]
Many thanks for the tag (https://github.com/damien-pous/coinduction/releases/tag/v1.8).
