### ISSUE TITLE
Release for Coq 8.19

### ISSUE THREAD

**Issue by palmskog** [damien-pous/coinduction#19]
Coq 8.19.0 is out, and unfortunately `coq-coinduction.1.8` gives the following error on this Coq version:
```
# File "src/reification.ml", line 227, characters 14-28:
# 227 |      tclTHEN (Tactics.revert [rname])
#                     ^^^^^^^^^^^^^^
# Error: Unbound value Tactics.revert
```
Hence, a new release is required for 8.19 support. For example, the release could be based on the current `master` branch (65d0207), which I have successfully tested on Coq 8.19.0. I'd be happy to help with adding a new package to the Coq opam archive based on a new release.

**Comment by damien-pous** [comment]
Hi @palmskog,
I've done a new version (tag v1.9) integrating some recent small additions. 
Here is the pull request for the opam package: https://github.com/coq/opam/pull/2987
Best,
Damien

**Comment by palmskog** [comment]
Thanks!
