### ISSUE TITLE
Where to find coq-coinduction-examples

### ISSUE THREAD

**Issue by Lysxia** [damien-pous/coinduction#7]
The README mentions a coq-coinduction-examples package, but it doesn't exist on Opam. Funnily, there's is a coq-coinductive-examples by Gimenez.

**Comment by damien-pous** [comment]
Indeed, my repo was private, and I had forgotten to turn it into a package...
repo is here: https://github.com/damien-pous/coinduction-example
package coq-coinduction-examples should land into opam pretty soon

Thanks @Lysxia !
