### ISSUE TITLE
Equivalence between Parrow and Weber's characterisation?

### ISSUE THREAD

**Issue by alxest** [damien-pous/coinduction#8]
Thanks for building such a clean, minimal, and impressive theory/library!!
I am interested in using the theorem [at the end of section 9](https://hal.archives-ouvertes.fr/hal-01259622/document), which connects the companion object with Parrow and Weber's characterisation. Has this been formalized here or somewhere else?

Best regards.

**Comment by damien-pous** [comment]
Hi,

A difficulty is that this characterisation, on paper, requires ordinals.

I provide an ordinal-free version of that characterisation towards the end of coinduction.v, in the module named "chain".
This is maybe not immediately apparent, but the subset "S" I defined there is the set of elements in the final sequence ; nicely, this set doesn't need ordinals to be defined, and is enough for what we want.
Then the definition of t' corresponds to Parrow & Weber's characterisation, and t and t' coincide (Theorem tt')

Does this make sense?

All the best,
Damien
