### ISSUE TITLE
Supporting indexed relations

### ISSUE THREAD

**Issue by YaZko** [damien-pous/coinduction#9]
Hello,

We have been working recently with @Lapin0t with relations over presheaves, i.e. given a fixed `I : Type`, `reli (T U: psh I)  := forall (i:I), T i -> T i -> Prop`, and defining such relations via the companion.
W.r.t. to definitions, it's been completely straightforwards: an instance of `CompleteLattice` for `reli A B` and porting the file `rel.v` to this setup.
However things are a bit harder to parse when it comes to the tactics: trying to run `coinduction r cih` fails with:

```
Error: Illegal application: 
The term "reification.coinduction" of type
 "forall (A : Arity) (c : reification.T) (b : mon (REL' A Prop)) (x : reification.fT A c) (_ : forall (R : REL' A Prop) (_ : reification.pT (coinduction.t b R) x), reification.pT (bt b R) x), reification.pT (gfp b) x"
cannot be applied to the terms
 "ABS I (fun i0 : I => ABS (itree E i i0) (fun _ : itree E i i0 => ABS (itree E i i0) (fun _ : itree E i i0 => PRP)))" : "Arity"
 "reification.hol" : "reification.T"
 "it_eq_map E eqᵢ" : "mon (forall (i0 : I) (_ : itree E i i0) (_ : itree E i i0), Prop)"
 "tuple (ABS I (fun i0 : I => ABS (itree E i i0) (fun _ : itree E i i0 => ABS (itree E i i0) (fun _ : itree E i i0 => PRP)))) X t t"
   : "PRD (ABS I (fun i0 : I => ABS (itree E i i0) (fun _ : itree E i i0 => ABS (itree E i i0) (fun _ : itree E i i0 => PRP))))"
The 3rd term has type "mon (forall (i0 : I) (_ : itree E i i0) (_ : itree E i i0), Prop)" which should be coercible to
 "mon (REL' (ABS I (fun i0 : I => ABS (itree E i i0) (fun _ : itree E i i0 => ABS (itree E i i0) (fun _ : itree E i i0 => PRP)))) Prop)".
```

I am slightly unsure what is going on, I naively assumed that `forall i, R i -> R i -> Prop` would be covered by the dependent arities supported (i.e. of the shape "[ABS X1 (fun x1 => ABS X2 (fun x2 => ... (ABS Xn (fun _ => PRP))))]" as described in `tactics.v`).

Would you know if I am misunderstanding the situation and have a hint as to what we need to extend to support our use case by any chance?

Thanks a bunch,
Yannick

**Comment by YaZko** [comment]
Looking at it more closely, the arity is correctly reified `)REL' (ABS I (fun i0 : I => ABS (itree E i i0) (fun _ : itree E i i0 => ABS (itree E i i0) (fun _ : itree E i i0 => PRP)))) Prop)` reduces as expected to `(forall (b : I) (_ : @itree I E i b) (_ : @itree I E i b), Prop)`.

However the terms disagree on the implicit arguments. The lemma `reification.coinduction` specifically wants the monotone function to be over a lattice instance explicitely built as a chain of `CompleteLattice_dfun` on top of `CompleteLattice_Prop`. On our side, we have a local instance `CompleteLatticeRelᵢ {I : Type} {A B : psh I} : CompleteLattice (relᵢ A B)` directly, hence the failure in unification I believe.

This seems to suggest that we got carried away by defining our own lattice instance rather than relying on the library's ones, but something seems amiss: although it seems like the right instances are there, it fails to be inferred automatically.

```
Goal forall (I : Type) (A : I  -> Type), CompleteLattice (forall (i : I), A i -> A i -> Prop).
  Fail typeclasses eauto.
  intros.
  apply CompleteLattice_dfun.
  intros ?.
  apply CompleteLattice_dfun.
  intros ?.
  apply CompleteLattice_dfun.
  intros ?.
  apply CompleteLattice_Prop.
Defined.
```

**Comment by YaZko** [comment]
Ah but that's because the library does not export the `CompleteLattice_dfun` instance, only the non-dependent `CompleteLattice_fun` one! 

If I reexport it locally and scratch our own instance, it works! 

Is there a reason for which this instance is kept local?

**Comment by damien-pous** [comment]
It seems there is no reason anymore for that, so now there is only the dependent instance, which is exported.
Do you confirm it's ok now?

**Comment by YaZko** [comment]
Yes I confirm, thanks a bunch!
